services:
  gateway:
    build: ./services/gateway
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - EVALUATOR_ENABLED=${EVALUATOR_ENABLED:-false}
      - EVALUATOR_INTERVAL_SEC=${EVALUATOR_INTERVAL_SEC:-600}
      - RAG_URL=${RAG_URL:-http://rag:8000}
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8000/health || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 5
      start_period: 10s
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  ui:
    build: ./services/ui
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    environment:
      - GATEWAY_URL=http://gateway:8000
  rag:
    build: ./services/rag
    ports:
      - "8001:8000"
    environment:
      - EMBEDDINGS_BACKEND=${EMBEDDINGS_BACKEND:-tfidf}
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8000/health || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 5
      start_period: 10s
