services:
  gateway:
    build: ./services/gateway
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - EVALUATOR_ENABLED=${EVALUATOR_ENABLED:-false}
      - EVALUATOR_INTERVAL_SEC=${EVALUATOR_INTERVAL_SEC:-600}
      - RAG_URL=${RAG_URL:-http://rag:8000}
      - OTEL_ENABLED=${OTEL_ENABLED:-false}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET:-}
      - SLACK_SIGNING_REQUIRED=${SLACK_SIGNING_REQUIRED:-false}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}
      - SLACK_DEFAULT_CHANNEL=${SLACK_DEFAULT_CHANNEL:-}
      - OPA_URL=${OPA_URL:-http://opa:8181}
    depends_on:
      - db
      - opa
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8000/ready || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 5
      start_period: 10s
  db:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  ui:
    build: ./services/ui
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    environment:
      - GATEWAY_URL=http://gateway:8000
  rag:
    build: ./services/rag
    ports:
      - "8001:8000"
    environment:
      - EMBEDDINGS_BACKEND=${EMBEDDINGS_BACKEND:-tfidf}
      - OTEL_ENABLED=${OTEL_ENABLED:-false}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-}
  mcp:
    build: ./services/mcp
    environment:
      - GATEWAY_URL=http://gateway:8000
    ports:
      - "8002:8000"
    depends_on:
      - gateway
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8000/health || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 5
      start_period: 10s

  opa:
    image: openpolicyagent/opa:latest
    command: ["run", "--server", "--addr=0.0.0.0:8181", "-b", "/policies"]
    ports:
      - "8181:8181"
    volumes:
      - ./services/opa/policies:/policies:ro
