name: gateway-smoke
on:
  push:
  pull_request:
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compose up db and gateway
        run: docker-compose up -d --build db gateway
      - name: Wait for gateway health
        run: |
          for i in {1..60}; do
            if curl -sf http://localhost:8000/health > /dev/null; then
              exit 0
            fi
            sleep 2
          done
          echo "Gateway not healthy"; docker-compose logs gateway; exit 1
      - name: Curl health
        run: curl -sS http://localhost:8000/health
