name: gateway-smoke
on:
  push:
  pull_request:
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compose up db and gateway
        run: docker compose up -d --build db gateway
      - name: Wait for gateway health
        run: |
          for i in {1..60}; do
            if curl -sf http://localhost:8000/health > /dev/null; then
              exit 0
            fi
            sleep 2
          done
          echo "Gateway not healthy"; docker compose logs gateway; exit 1
      - name: Curl health
        run: curl -sS http://localhost:8000/health
      - name: Exercise policy
        run: |
          curl -sS -X POST http://localhost:8000/v1/policy/evaluate \
            -H 'content-type: application/json' \
            -d '{"kind":"stale_pr"}' | jq .
      - name: Exercise workflows
        run: |
          curl -sS -X POST http://localhost:8000/v1/workflows/run \
            -H 'content-type: application/json' \
            -d '{"rule_kind":"stale_pr","subject":"pr:ci"}' | jq .
          curl -sS http://localhost:8000/v1/workflows/jobs | jq . | head -20
      - name: Exercise approvals
        run: |
          APPROVAL_ID=$(curl -sS -X POST http://localhost:8000/v1/workflows/run \
            -H 'content-type: application/json' \
            -d '{"rule_kind":"stale_pr","subject":"pr:ci-approve","action":"block"}' | jq -r '.action_id')
          curl -sS -X POST http://localhost:8000/v1/approvals/$APPROVAL_ID/decision \
            -H 'content-type: application/json' \
            -d '{"decision":"approve","reason":"ok"}' | jq .
          curl -sS http://localhost:8000/v1/workflows/jobs | jq . | head -20
