name: retention-purge

on:
  schedule:
    - cron: "0 6 * * *" # daily at 06:00 UTC
  workflow_dispatch: {}

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install psycopg
        run: |
          python -m pip install --upgrade pip
          pip install "psycopg[binary]"
      - name: Purge old events (no-op if DATABASE_URL unset)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RETENTION_DAYS: 30
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "DATABASE_URL not set, skipping purge"; exit 0; fi
          python services/metrics/scripts/purge_old_events.py

